### ISSUE TITLE
麻烦你对代码架构做一下介绍，谢谢。

### ISSUE THREAD

**Issue by ybxgood** [wangwindows/kongqi123#1]

**Comment by wangwindows** [comment]
src目录是源文件

src/spider是蜘蛛程序的源文件的目录
src/spider/spiders是２个爬虫文件的目录
其它文件是蜘蛛数据结构和配置

src/web是网站程序的源文件的目录
src/web/static是静态文件
src/web/www是web页面程序和模板
其它是web数据结构和配置

run.py是启动测试环境的入口
server.py是正式环境的入口

config.ini
config.py
supvervisord.conf
这三个都是配置文件

task.py是后台计划任务的入口
